# Generated by Django 5.0.6 on 2024-09-08 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_reel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reel_stream_following', to=settings.AUTH_USER_MODEL)),
                ('reel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_stream_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
