# Generated by Django 5.0.6 on 2024-09-10 12:23

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_reellikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=post.models.user_directory_path, verbose_name='thumbnail'),
            preserve_default=False,
        ),
    ]
