# Generated by Django 5.0.6 on 2024-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_bio_profile_first_name_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
