# Generated by Django 5.0.6 on 2024-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_profile_is_online_profile_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.png', null=True, upload_to='profile_pciture'),
        ),
    ]
