# Generated by Django 5.0.6 on 2024-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_picture'),
        ),
    ]
