# Generated by Django 5.0.6 on 2024-09-15 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 13, 2, 16, 103163, tzinfo=datetime.timezone.utc)),
        ),
    ]
