# Generated by Django 5.0.6 on 2024-09-15 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_status_expires_at_highlight_highlightitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightitem',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='highlightitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 13, 9, 59, 524423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
        migrations.DeleteModel(
            name='HighlightItem',
        ),
    ]
