# Generated by Django 5.0.6 on 2024-09-15 13:14

import datetime
import django.db.models.deletion
import status.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_remove_highlightitem_highlight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 13, 14, 26, 517255, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to=status.models.user_directory_path, verbose_name='cover')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statuses', models.ManyToManyField(related_name='highlights', to='status.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
